<a href="https://colab.research.google.com/github/InduwaraRathnayake/In22-S4-CS3111-Intro-to-ML/blob/week2/Week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Framing ML problem and feature encoding

## 1. One-hot encoding



This section focuses on preparing the data for machine learning
by applying one-hot encoding to categorical features.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/In22-S4-CS3111 - Intro to ML/data-one-hot-encoder.csv")

In [ ]:
df.head() # Display the top 5 rows of the dataframe

Id Colour Country
0   1    Red     USA
1   2    Red     USA
2   3   Blue      UK
3   4  Green  Canada
4   5  Green  Canada

In [ ]:
df.tail() # Display the bottom 5 rows of the dataframe

Id Colour Country
295  296   Blue     USA
296  297  Green     USA
297  298  Green      UK
298  299  Green  Canada
299  300   Blue     USA

In [ ]:
df.dtypes #data type of columns

Id          int64
Colour     object
Country    object
dtype: object

In [ ]:
df["Colour"].unique() # Get unique values in the 'Colour' column

array(['Red', 'Blue', 'Green'], dtype=object)

In [ ]:
df["Country"].unique() # Get unique values in the 'Country' column

array(['USA', 'UK', 'Canada'], dtype=object)

In [ ]:
ohe = OneHotEncoder() # Create a OneHotEncoder object
print(ohe)

OneHotEncoder()


In [ ]:
ohe.fit_transform(df[["Colour", "Country"]]).toarray()

array([[0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [ ]:
feature_array = ohe.fit_transform(df[["Colour", "Country"]]).toarray() # Apply one-hot encoding to the 'Colour' and 'Country' columns
print(feature_array)

[[0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [ ]:
ohe.categories_

[array(['Blue', 'Green', 'Red'], dtype=object),
 array(['Canada', 'UK', 'USA'], dtype=object)]

In [ ]:
feature_labels = ohe.categories_ # Get the categories identified by the OneHotEncoder

In [ ]:
# save the 2 arrays into 1 array
np.array(feature_labels).ravel()

array(['Blue', 'Green', 'Red', 'Canada', 'UK', 'USA'], dtype=object)

In [ ]:
feature_labels = np.array(feature_labels).ravel() # Flatten the feature labels array
print(feature_labels)

['Blue' 'Green' 'Red' 'Canada' 'UK' 'USA']


In [ ]:
pd.DataFrame(feature_array, columns=feature_labels) # Create a dataframe from the feature array and labels

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]

In [ ]:
features = pd.DataFrame(feature_array, columns=feature_labels)

In [ ]:
print(features)

     Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]


In [ ]:
features.head()

Blue  Green  Red  Canada   UK  USA
0   0.0    0.0  1.0     0.0  0.0  1.0
1   0.0    0.0  1.0     0.0  0.0  1.0
2   1.0    0.0  0.0     0.0  1.0  0.0
3   0.0    1.0  0.0     1.0  0.0  0.0
4   0.0    1.0  0.0     1.0  0.0  0.0

In [ ]:
# Concatenate the original dataframe with the encoded features
pd.concat([df, features], axis=1)

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0      1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1      2    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
2      3   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
3      4  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
4      5  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
..   ...    ...     ...   ...    ...  ...     ...  ...  ...
295  296   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0
296  297  Green     USA   0.0    1.0  0.0     0.0  0.0  1.0
297  298  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
298  299  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
299  300   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 9 columns]

In [ ]:
df_new = pd.concat([df, features], axis=1)

In [ ]:
df_new.head()

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0   1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1   2    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
2   3   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
3   4  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
4   5  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0

---


## 2. Ordinal Encording

This section focuses on preparing the data for machine learning by applying ordinal encoding to categorical features that have an inherent order or ranking.

In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/In22-S4-CS3111 - Intro to ML/ordinal.csv") # Load the dataset

In [ ]:
df.head() # Display the first few rows of the dataframe

Id  Education Country
0   1        PhD     USA
1   2    Masters      UK
2   3  Bachelors  Canada
3   4        PhD     USA
4   5    Masters     USA

In [ ]:
df["Education"].unique() # Get unique values in the 'Education' column

array(['PhD', 'Masters', 'Bachelors'], dtype=object)

In [ ]:
enc = OrdinalEncoder() # Create an OrdinalEncoder object

In [ ]:
print(enc)

OrdinalEncoder()


In [ ]:
enc.fit_transform(df[["Education"]]) # Fit and transform the 'Education' column

array([[2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],

In [ ]:
df["Education"] = enc.fit_transform(df[["Education"]]) # Replace the 'Education' column with encoded values

In [ ]:
df.head()

Id  Education Country
0   1        2.0     USA
1   2        1.0      UK
2   3        0.0  Canada
3   4        2.0     USA
4   5        1.0     USA

### We can also add the categories manually

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/In22-S4-CS3111 - Intro to ML/ordinal.csv") # Load the dataset

In [ ]:
education = ['PhD', 'Masters', 'Bachelors'] # Define the order of categories

In [ ]:
enc = OrdinalEncoder(categories=[education]) # Create an OrdinalEncoder with specified categories

In [ ]:
enc.fit_transform(df[["Education"]])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],

In [ ]:
df["Education"] = enc.fit_transform(df[["Education"]])

In [ ]:
df.head()

Id  Education Country
0   1        0.0     USA
1   2        1.0      UK
2   3        2.0  Canada
3   4        0.0     USA
4   5        1.0     USA