<a href="https://colab.research.google.com/github/InduwaraRathnayake/In22-S4-CS3111-Intro-to-ML/blob/main/Week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Framing ML problem and feature encoding


This section focuses on preparing the data for machine learning
by applying one-hot encoding to categorical features.

## 1. One-hot encoding


In [30]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [31]:
# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/In22-S4-CS3111 - Intro to ML/data-one-hot-encoder.csv")

In [32]:
df.head() # Display the top 5 rows of the dataframe

Id Colour Country
0   1    Red     USA
1   2    Red     USA
2   3   Blue      UK
3   4  Green  Canada
4   5  Green  Canada

In [33]:
df.tail() # Display the bottom 5 rows of the dataframe

Id Colour Country
295  296   Blue     USA
296  297  Green     USA
297  298  Green      UK
298  299  Green  Canada
299  300   Blue     USA

In [34]:
df.dtypes #data type of columns

Id          int64
Colour     object
Country    object
dtype: object

In [35]:
df["Colour"].unique() # Get unique values in the 'Colour' column

array(['Red', 'Blue', 'Green'], dtype=object)

In [36]:
df["Country"].unique() # Get unique values in the 'Country' column

array(['USA', 'UK', 'Canada'], dtype=object)

In [37]:
ohe = OneHotEncoder() # Create a OneHotEncoder object
print(ohe)

OneHotEncoder()


In [38]:
ohe.fit_transform(df[["Colour", "Country"]]).toarray()

array([[0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [39]:
feature_array = ohe.fit_transform(df[["Colour", "Country"]]).toarray() # Apply one-hot encoding to the 'Colour' and 'Country' columns
print(feature_array)

[[0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [40]:
ohe.categories_

[array(['Blue', 'Green', 'Red'], dtype=object),
 array(['Canada', 'UK', 'USA'], dtype=object)]

In [41]:
feature_labels = ohe.categories_ # Get the categories identified by the OneHotEncoder

In [42]:
# save the 2 arrays into 1 array
np.array(feature_labels).ravel()

array(['Blue', 'Green', 'Red', 'Canada', 'UK', 'USA'], dtype=object)

In [43]:
feature_labels = np.array(feature_labels).ravel() # Flatten the feature labels array
print(feature_labels)

['Blue' 'Green' 'Red' 'Canada' 'UK' 'USA']


In [44]:
pd.DataFrame(feature_array, columns=feature_labels) # Create a dataframe from the feature array and labels

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]

In [45]:
features = pd.DataFrame(feature_array, columns=feature_labels)

In [46]:
print(features)

     Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]


In [47]:
features.head()

Blue  Green  Red  Canada   UK  USA
0   0.0    0.0  1.0     0.0  0.0  1.0
1   0.0    0.0  1.0     0.0  0.0  1.0
2   1.0    0.0  0.0     0.0  1.0  0.0
3   0.0    1.0  0.0     1.0  0.0  0.0
4   0.0    1.0  0.0     1.0  0.0  0.0

In [48]:
# Concatenate the original dataframe with the encoded features
pd.concat([df, features], axis=1)

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0      1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1      2    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
2      3   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
3      4  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
4      5  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
..   ...    ...     ...   ...    ...  ...     ...  ...  ...
295  296   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0
296  297  Green     USA   0.0    1.0  0.0     0.0  0.0  1.0
297  298  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
298  299  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
299  300   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 9 columns]

In [49]:
df_new = pd.concat([df, features], axis=1)

In [50]:
df_new.head()

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0   1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1   2    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
2   3   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
3   4  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
4   5  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0